version: '3'

services:
  crm_mysql:
    container_name: crm_mysql
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: a1b2c3d4e5
      MYSQL_DATABASE: crm_db
      MYSQL_USER: crm_dba
      MYSQL_PASSWORD: a1b2c3d4e5
      TZ: America/Sao_Paulo
    # ports:
    #   - "3308:3306"

  crm_web:
    depends_on:
     - crm_mysql
    # Imagem x86-64 & arm64 juntas com todos os modulos
    image: reg.gitcoy.net/arquivos/perfex:2.9.4_modulos
     
    # Imagem arm64 Basica sem modulos
    #image: reg.gitcoy.net/arquivos/perfex:2.9.4-arm64

    # Imagem x86-64 Basica sem modulos
    #image: reg.gitcoy.net/arquivos/perfex:2.9.4-x86-64
    
    #build: .
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - www_files:/var/www/html
    expose:
      - 80
    ports:
      - 9999:80
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=crm.gitnotfound.dev.br
      - LETSENCRYPT_HOST=crm.gitnotfound.dev.br
      - VIRTUAL_PORT=80
      - TZ=America/Sao_Paulo
    container_name: crm_web

volumes:
  db_data:
  www_files:
 
networks:
  perfex_web:
    external: true